/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_design_JniTestStatic */

#ifndef _Included_com_example_design_JniTestStatic
#define _Included_com_example_design_JniTestStatic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_design_JniTestStatic
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_design_JniTestStatic_hello
(JNIEnv *, jobject);

/*
 * Class:     com_example_design_JniTestStatic
 * Method:    getHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_design_JniTestStatic_getHello
        (JNIEnv *, jobject);

/*
 * Class:     com_example_design_JniTestStatic
 * Method:    getA
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_design_JniTestStatic_getA
        (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
